global:
  scrape_interval: 15s # prometheus가 해당 컴포넌트를 얼마나 자주 스크랩 하는지
  evaluation_interval: 15s

rule_files:
  - "/etx/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9091']

  - job_name: 'coupon-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'point-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8083']

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # alertmanager:9093 # 추후 AlertManager 추가 시 주석 해제